packet_length_poll: 0.26624
packet_length_response: 0.45056
speed_of_sound: 1500
algorithm: 


agent:
  modem: 
    id: 0
    delay_time: 0.0
    packet_reception_rate: 1.0
    dst: 'broadcast'
    packet_type: 'TYPE_RANGING_ACK'
    position: []  # what is this position for?
anchors: 
  dst: 'broadcast'
  packet_type: 'TYPE_RANGING_ACK'
  anchor_1: 
    position: [-10.0, -10.0, -1.0]
    modem: 
      id: 1
      delay_time: 0.0
      packet_reception_rate: 1.0   
      # dst: 'broadcast'    # the same for all anchors? - move these to anchors
      # packet_type: 'TYPE_RANGING_ACK'
  anchor_2:
    position: [-10.0, 10.0, -1.0]
    modem: 
      id: 2
      delay_time: 0.7
      packet_reception_rate: 1.0   
      # dst: 'broadcast'
      # packet_type: 'TYPE_RANGING_ACK'
  anchor_3: 
    position: [10.0, 10.0, -1.0]
    modem: 
      id: 3
      delay_time: 1.4
      packet_reception_rate: 1.0
  anchor_4:
    position: [-10.0, -10.0, -1.0]
    modem: 
      id: 4
      delay_time: 2.1
      packet_reception_rate: 1.0

